/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  tutorialSidebar: [{ type: 'autogenerated', dirName: '.' }], // But you can create a sidebar manually
  xrSidebar: [{type: 'autogenerated', dirName: 'XRMode'}],
  pcSidebar: [{type: 'autogenerated', dirName: 'PCMode'}],
  generalGuideSidebar: [{type: 'autogenerated', dirName: 'GeneralGuide'}],
  behaviourBlockGuideSidebar: [{type: 'autogenerated', dirName: 'BehaviourOverview'}],
  behaviourOverviewSidebar: [{ type: 'autogenerated', dirName: 'BehaviourOverview' }],
  FAQSidebar: [
    {type: 'autogenerated', dirName: 'FAQ'},
    {
      type: 'link',
      label: 'Join our Discord',
      href: 'https://discord.gg/Fq86WKbtaN'
    },
    {
      type: 'link',
      label: 'Go to our Youtube Channel', 
      href: 'https://www.youtube.com/@XRCCForYou'
    },
  ],
  TutorialVideoSidebar: [
    { type: 'autogenerated', dirName: 'Tutorial' },
    {
      type: 'link',
      label: 'Video Tutorial Playlist', 
      href: 'https://www.youtube.com/playlist?list=PLcEOBnmWXd3ljgBpkI8pD_5yY1nYTvlZB'
    },],
};

export default sidebars;
